= vertx-warp10-metrics
:source-language: java

== About

Warp10 is an http://www.warp10.io[open source platform for time series analysis].

The http://vertx.io/docs/vertx-core/java/index.html#_metrics_spi[Vert.x Metrics SPI] allows implementers to
capture events from Vert.x in order to gather metrics.

This project is an implementation of the Vert.x Metrics SPI. Metrics built from Vert.x events will sent to a Warp10 platform throw https://github.com/cityzendata/sensision[Sensision] agent

== Quickstart

Follow the http://www.warp10.io/getting-started/[instructions] to get Warp10 up and running.

Ten clone this project and build it:
[source, bash]
----
git clone https://github.com/slambour/vertx-warp10-metrics.git
cd vertx-warp10-metrics
 mvn clean install
----

Once the project is built, add the dependency to your Vert.x 3 project. For Maven based projects:
[source, xml]
----
<parent>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-warp10-metrics</artifactId>
 <version>3.3.0-SNAPSHOT</version>
</parent>
----

Then, you must enable Vert.x Metrics programmatically:
[source, java]
----
VertxWarp10Options vertxWarp10Options = new VertxWarp10Options();
vertxWarp10Options.setEnabled(true); // By default Vert.x Metrics is disabled

VertxOptions vertxOptions = new VertxOptions();
vertxOptions.setMetricsOptions(vertxWarp10Options);

Vertx vertx = Vertx.vertx(vertxOptions);
----

or via with system properties:
[source, bash]
----
-Dvertx.metrics.options.enabled=true
----

== Configuration
 
If you are running with Warp10 docker image, Sensision agent have to write metrics inside the data folder configured by volume mapping.
All Sensision configuration works with system properties 

[source, bash]
----
-Dsensision.home=/var/warp10/sensision/data   
-Dsensision.events.dir=/var/warp10/sensision/data/metrics   
-Dsensision.dump.period=60000   
-Dsensision.dump.currentts=true 
-Dsensision.dump.onexit=true
----

== Documentation

Asciidoc documentation is generated by the build in src/main/asciidoc folder. With: 

<1> Getting started sections
<2> All metrics available
<3> Access to your metrics with http://www.warp10.io/reference/[WarpScript]

== License

Source available under the terms of Apache License v2.0.

The Apache License v2.0 is available at:
http://www.opensource.org/licenses/apache2.0.php





